### ISSUE TITLE
小米6500pro新款路由

### ISSUE THREAD

**Issue by DailinC** [thun888/mirouter-ui#13]
修改好了配置文件之后无法使用

time="2023-11-09T04:59:59Z" level=info msg="配置文件路径为:/app/data/config.json"
time="2023-11-09T04:59:59Z" level=debug msg="静态资源目录为:/app/data/static"
time="2023-11-09T04:59:59Z" level=debug msg="获取路由器信息..."
time="2023-11-09T05:00:28Z" level=info msg="更新token..."
panic: interface conversion: interface {} is nil, not float64

goroutine 1 [running]:
main/modules/login.GetToken({0xc00022ef94, 0xc}, {0xc000189ea0, 0x20}, {0xc00022efb0, 0xc})
	/app/modules/login/base.go:131 +0x9e7
main.gettoken({0xc000252440?, 0x1, 0x1?})
	/app/main.go:116 +0x13a
main.main()
	/app/main.go:255 +0x5d1
time="2023-11-09T05:00:54Z" level=info msg="配置文件路径为:/app/data/config.json"
time="2023-11-09T05:00:54Z" level=debug msg="静态资源目录为:/app/data/static"
time="2023-11-09T05:00:54Z" level=debug msg="获取路由器信息..."
time="2023-11-09T05:01:05Z" level=info msg="配置文件路径为:/app/data/config.json"
time="2023-11-09T05:01:05Z" level=debug msg="静态资源目录为:/app/data/static"
time="2023-11-09T05:01:05Z" level=debug msg="获取路由器信息..."

**Comment by DailinC** [comment]
补充一条，在nas上安装docker启动后日志如下

time="2023-11-09T04:41:33Z" level=info msg="配置文件路径为:/app/data/config.json"
time="2023-11-09T04:41:33Z" level=debug msg="静态资源目录为:/app/data/static"
time="2023-11-09T04:41:33Z" level=debug msg="获取路由器信息..."
time="2023-11-09T04:41:33Z" level=debug msg="路由器型号为:RD08"
time="2023-11-09T04:41:33Z" level=debug msg="路由器名称为:DailinWorld"
time="2023-11-09T04:41:33Z" level=debug msg="使用新加密模式"
time="2023-11-09T04:41:33Z" level=info msg="当前路由器可能无法正常获取某些数据！"
time="2023-11-09T04:41:33Z" level=info msg="更新token..."
time="2023-11-09T04:41:33Z" level=info msg="登录失败，请检查配置"
time="2023-11-09T04:41:33Z" level=info msg="5秒后退出程序"
time="2023-11-09T04:41:33Z" level=info msg="{\"code\":401,\"msg\":\"not auth\"}"

新款路由可能加密方式不同

**Comment by DailinC** [comment]
Sorry,由于换了路由器，密码配置错误，不过很奇怪的是本地的docker和二进制都不好用，反而是nas上的docker可以使用
